# Generated by Django 5.2.7 on 2025-11-06 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_reader_book_reader'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(unique=True)),
                ('slug', models.CharField(unique=True)),
            ],
        ),
        migrations.AlterModelManagers(
            name='book',
            managers=[
            ],
        ),
        migrations.AddField(
            model_name='book',
            name='category',
            field=models.ManyToManyField(blank=True, related_name='books', to='book.category'),
        ),
    ]
