# Generated by Django 5.2.8 on 2025-11-09 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0004_cycle_alter_book_options_book_cycle_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='image_url',
            field=models.CharField(default=1, unique=True),
            preserve_default=False,
        ),
    ]
